In [1]:
import numpy as np

In [2]:
arr= ["Fahad",1,[1.22,4.7]]

In [3]:
np_arr = np.array([arr])
print(np_arr)

[['Fahad' 1 list([1.22, 4.7])]]


/tmp/ipykernel_6607/3169140000.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_arr = np.array([arr])


In [4]:
np_arr[0,2][1]

4.7

In [5]:
np_arr[0,2][1]=100
np_arr

array([['Fahad', 1, list([1.22, 100])]], dtype=object)

In [6]:
string_arr = ["Fahad","Hafiza","Ahad"]
np_string_arr = np.array(string_arr , np.str_)
print(np_string_arr)

['Fahad' 'Hafiza' 'Ahad']


In [7]:
np_string_arr.shape

(3,)

In [8]:
np_string_arr.dtype

dtype('<U6')

In [9]:
x=1
y=2
[x,y]=[y,x]
print(x)
print(y)

2
1


# Array Creation in Numpy

In [10]:
#1.Conversion from other Python structures (i.e. lists and tuples)
list_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("============================ LIST ARRAY ===========================")
print(list_array)
print("============================== SHAPE ==============================")
print(list_array.shape)
print("=============================== DATA TYPE =========================")
print(list_array.dtype)
print("=============================== SIZE ==============================")
print(list_array.size)

============================ LIST ARRAY ===========================
[[1 2 3]
 [4 5 6]
 [7 8 9]]
============================== SHAPE ==============================
(3, 3)
=============================== DATA TYPE =========================
int64
=============================== SIZE ==============================
9


In [14]:
#2.Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
print("============================= ARANGE =============================")
arange = np.arange(99)
print(arange)
print("============================= ZEROS ==============================")
zeros = np.zeros((3,6))
print(zeros)
print("============================= ONES ===============================")
ones = np.ones((6,9))
print(ones)
print("============================= LINSPACE ===========================")
linspace = np.linspace (1,2,20)
print(linspace )
print("============================= EMPTY ==============================")
empty = np.empty ((5,5))
print(empty)
print("========================== EMPTY LIKE ============================")
empty_like = np.empty_like(linspace)
print(empty_like)
print("========================== IDENTITY ===============================")
identity = np.identity(45)
print(identity)

============================= ARANGE =============================
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
============================= ZEROS ==============================
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
============================= ONES ===============================
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
============================= LINSPACE ===========================
[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.842

In [17]:
arr = arange.reshape(3,33)
print(arr)
arr = arr.ravel()
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


# Axis

In [18]:
x= [[1,2,3],[4,5,6],[7,8,9]]
arr  = np.array(x)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#sum of all columns
arr.sum(axis=0)

array([12, 15, 18])

In [22]:
#sum of all rows
arr.sum(axis=1)

array([ 6, 15, 24])

In [23]:
#transpose
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
#flatting thenumpy array
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [32]:
#number of dimension
arr.ndim

2

In [33]:
arr.nbytes

72

In [39]:
#indexes with miniimum and maximum value
list_ = np.array([9,8,7,6])
print(list_.argmin())
print(list_.argmax())

3
0


In [40]:
#arrangment of indexes in sorted form
list_ = np.array([7,6,4,7,9,2])
list_.argsort()

array([5, 2, 1, 0, 3, 4])

In [44]:
#argmax and argsort with 2d numpy array 
x_list= [[22,55,121],[14,544,6],[77,38,19]]
x  = np.array(x_list)
print('___________ARGMAX______________')
print(x.argmax())
print('___________ARGMAX WITH AXIS = 0______________')
print(x.argmax(axis=0))
print('___________ARGMAX WITH AXIS = 1______________')
print(x.argmax(axis=1))
print('___________ARGSORT______________')
print(x.argsort())

___________ARGMAX______________
4
___________ARGMAX WITH AXIS = 0______________
[2 1 0]
___________ARGMAX WITH AXIS = 1______________
[2 1 0]
___________ARGSORT______________
[[0 1 2]
 [2 0 1]
 [2 1 0]]


# Mathematical Operations


In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,4,7],[2,5,8],[3,6,9]])
print("__________ADDITION___________")
print(a + b)
print("__________MULTIPLICATION______")
print(a * b)
print("__________SQUARE ROOT_________")
print(np.sqrt(a))
print("_________MIN/MAX______________")
print(a.max())
print(a.min())

__________ADDITION___________
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
__________MULTIPLICATION______
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
__________SQUARE ROOT_________
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
_________MIN/MAX______________
9
1


# Finding element in array 

In [53]:
#where
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.where(a>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [54]:
np.count_nonzero(a)

9

In [55]:
np.nonzero(a)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

# Size of element

In [56]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)

32

In [58]:
sys.getsizeof(1) * len(py_ar)

112

In [60]:
np_ar.itemsize * np_ar.size

32

for more : https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html